version: '2'

services:
    telegram-proxy:
        image: telegrammessenger/proxy:latest
        container_name: mtproxy
        ports:
          - "${PORT:-443}:443"
        volumes:
           - "./data:/data"
        restart: always
        env_file:
           - ./config.env